// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafePath.Infrastructure.Persistence;

#nullable disable

namespace SafePath.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260811173100_AddGeofencing")]
    partial class AddGeofencing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafePath.Domain.Entities.EmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumberE164")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "IsActive");

                    b.ToTable("EmergencyContacts", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Families", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.FamilyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("InviteeEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("InviteeLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LinkToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FamilyId");

                    b.HasIndex("LinkToken")
                        .IsUnique();

                    b.ToTable("FamilyInvitations", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = TRUE");

                    b.HasIndex("FamilyId", "UserId")
                        .IsUnique();

                    b.ToTable("FamilyMembers", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.GeofenceActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("CompletedVisitDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("MemberUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RetainUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SafeZoneDisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("SafeZoneId")
                        .HasColumnType("uuid");

                    b.Property<int>("Transition")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RetainUntilUtc");

                    b.HasIndex("SafeZoneId");

                    b.HasIndex("VisitId");

                    b.HasIndex("MemberUserId", "OccurredAtUtc");

                    b.ToTable("GeofenceActivities", null, t =>
                        {
                            t.HasCheckConstraint("CK_GeofenceActivities_Transition", "\"Transition\" BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("SafePath.Domain.Entities.GeofenceCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MemberUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegistrationGeneration")
                        .HasColumnType("integer");

                    b.Property<Guid>("SafeZoneId")
                        .HasColumnType("uuid");

                    b.Property<int>("Transition")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("MemberUserId");

                    b.HasIndex("SafeZoneId", "MemberUserId", "OccurredAtUtc");

                    b.ToTable("GeofenceCandidates", null, t =>
                        {
                            t.HasCheckConstraint("CK_GeofenceCandidates_Generation", "\"RegistrationGeneration\" > 0");

                            t.HasCheckConstraint("CK_GeofenceCandidates_Transition", "\"Transition\" BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("SafePath.Domain.Entities.GeofenceConfirmationCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntendedTransition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RegistrationGeneration")
                        .HasColumnType("integer");

                    b.Property<Guid>("SafeZoneId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberUserId");

                    b.HasIndex("State", "LastObservedAtUtc");

                    b.HasIndex("SafeZoneId", "MemberUserId", "RegistrationGeneration", "IntendedTransition")
                        .IsUnique();

                    b.ToTable("GeofenceConfirmationCandidates", null, t =>
                        {
                            t.HasCheckConstraint("CK_GeofenceConfirmationCandidates_Generation", "\"RegistrationGeneration\" > 0");

                            t.HasCheckConstraint("CK_GeofenceConfirmationCandidates_State", "\"State\" BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_GeofenceConfirmationCandidates_Transition", "\"IntendedTransition\" BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("SafePath.Domain.Entities.GeofenceFeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("ActivityId", "RecipientUserId")
                        .IsUnique();

                    b.HasIndex("RecipientUserId", "CreatedAtUtc");

                    b.ToTable("GeofenceFeedItems", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.GeofenceRoutineJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeedItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastFailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("FeedItemId")
                        .IsUnique();

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("State", "NextAttemptAtUtc");

                    b.ToTable("GeofenceRoutineJobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_GeofenceRoutineJobs_State", "\"State\" BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("SafePath.Domain.Entities.LocationPing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("double precision");

                    b.Property<int?>("BatteryPercent")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAtUtc");

                    b.ToTable("LocationPings", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.RecipientQuietHours", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<TimeOnly>("LocalEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("LocalStart")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId")
                        .IsUnique();

                    b.ToTable("RecipientQuietHours", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SafeZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedMemberUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomName")
                        .HasColumnType("text");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<bool>("NotifyAssignedMember")
                        .HasColumnType("boolean");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("double precision");

                    b.Property<int>("Sensitivity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMemberUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FamilyId", "AssignedMemberUserId", "IsActive");

                    b.ToTable("SafeZones", null, t =>
                        {
                            t.HasCheckConstraint("CK_SafeZones_Category", "\"Category\" BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_SafeZones_Sensitivity", "\"Sensitivity\" BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SafeZoneRecipient", b =>
                {
                    b.Property<Guid>("SafeZoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.HasKey("SafeZoneId", "RecipientUserId");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("SafeZoneRecipients", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SafeZoneRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SafeZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MemberUserId");

                    b.HasIndex("SafeZoneId", "Generation")
                        .IsUnique();

                    b.ToTable("SafeZoneRegistrations", null, t =>
                        {
                            t.HasCheckConstraint("CK_SafeZoneRegistrations_Generation", "\"Generation\" > 0");
                        });
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SafeZoneRegistrationActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("SafeZoneRegistrationId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StateChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SafeZoneRegistrationId")
                        .IsUnique();

                    b.HasIndex("State", "StateChangedAtUtc");

                    b.ToTable("SafeZoneRegistrationActivations", null, t =>
                        {
                            t.HasCheckConstraint("CK_SafeZoneRegistrationActivations_State", "\"State\" BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SharingPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecipientMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipientMemberId");

                    b.HasIndex("FamilyId", "OwnerUserId");

                    b.HasIndex("OwnerUserId", "DataType");

                    b.ToTable("SharingPreferences", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SosDeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmergencyContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SosSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SosSessionId", "EmergencyContactId", "Channel")
                        .IsUnique()
                        .HasFilter("\"EmergencyContactId\" IS NOT NULL");

                    b.HasIndex("SosSessionId", "RecipientUserId", "Channel")
                        .IsUnique()
                        .HasFilter("\"RecipientUserId\" IS NOT NULL");

                    b.ToTable("SosDeliveryAttempts", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SosSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double?>("AccuracyMeters")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CanceledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CanceledByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LiveWindowEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TriggeredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TriggeredByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredByUserId");

                    b.HasIndex("FamilyId", "TriggeredAtUtc");

                    b.ToTable("SosSessions", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumberE164")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime?>("ProfileUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.UserDeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserDeviceTokens", (string)null);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.EmergencyContact", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.FamilyInvitation", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.GeofenceActivity", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MemberUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafePath.Domain.Entities.SafeZone", null)
                        .WithMany()
                        .HasForeignKey("SafeZoneId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.GeofenceCandidate", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MemberUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafePath.Domain.Entities.SafeZone", null)
                        .WithMany()
                        .HasForeignKey("SafeZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.GeofenceConfirmationCandidate", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MemberUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafePath.Domain.Entities.SafeZone", null)
                        .WithMany()
                        .HasForeignKey("SafeZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.GeofenceFeedItem", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.GeofenceActivity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.GeofenceRoutineJob", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.GeofenceFeedItem", null)
                        .WithMany()
                        .HasForeignKey("FeedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.LocationPing", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.RecipientQuietHours", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SafeZone", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedMemberUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafePath.Domain.Entities.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SafeZoneRecipient", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafePath.Domain.Entities.SafeZone", null)
                        .WithMany()
                        .HasForeignKey("SafeZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SafeZoneRegistration", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MemberUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SafePath.Domain.Entities.SafeZone", null)
                        .WithMany()
                        .HasForeignKey("SafeZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SafeZoneRegistrationActivation", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.SafeZoneRegistration", null)
                        .WithMany()
                        .HasForeignKey("SafeZoneRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SharingPreference", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafePath.Domain.Entities.FamilyMember", null)
                        .WithMany()
                        .HasForeignKey("RecipientMemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SosDeliveryAttempt", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.SosSession", null)
                        .WithMany()
                        .HasForeignKey("SosSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.SosSession", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SafePath.Domain.Entities.UserDeviceToken", b =>
                {
                    b.HasOne("SafePath.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
